{
 "title": "Camunda",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  {
   "title": "Started / Finished Tasks",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT 'started' metric, count(*) value, 0 time_sec FROM ACT_HI_TASKINST \nWHERE $__timeFilter(START_TIME_)\nUNION ALL\nSELECT 'finished' metric, count(*) value, 0 FROM ACT_HI_TASKINST \nWHERE $__timeFilter(END_TIME_)\norder by 1,2\n"
    }
   ]
  },
  {
   "title": "Counts by Task Name",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT NAME_ metric, 1 value, UNIX_TIMESTAMP(START_TIME_) time_sec FROM ACT_HI_TASKINST \nWHERE $__timeFilter(START_TIME_)\norder by START_TIME_\n\n\n"
    }
   ]
  },
  {
   "title": "Expenses Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT NAME_ name, unix_timestamp(START_TIME_) time_sec, 0 is_end FROM ACT_HI_TASKINST \nWHERE $__timeFilter(START_TIME_)\nUNION ALL\nSELECT NAME_ name, unix_timestamp(END_TIME_) time_sec, 1 is_end FROM ACT_HI_TASKINST \nWHERE $__timeFilter(END_TIME_)\norder by 2,3\n"
    }
   ]
  },
  {
   "title": "Successful Engagements Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(successful) as value\nFROM summary\nWHERE $__timeFilter(closure_datetime) AND successful = 1"
    }
   ]
  },
  {
   "title": "Successful Engagement Ratio Overall",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n   (sum(successful) / (SELECT count(*) FROM summary)) as value\nFROM summary\nWHERE $__timeFilter(closure_datetime)\nORDER BY closure_datetime ASC\n"
    }
   ]
  },
  {
   "title": "Total Engagement Cost",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(payment) as value\nFROM payments"
    }
   ]
  },
  {
   "title": "Average Engagement Cost",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(payment) as value\nFROM payments\nWHERE $__timeFilter(payment_datetime)\nORDER BY payment_datetime ASC\n"
    }
   ]
  },
  {
   "title": "Successful Engagements Count Per Employee",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(closure_datetime) as time_sec,\n  (SUM(successful)/(SELECT COUNT(*) FROM employees)) as value\nFROM summary\nWHERE $__timeFilter(closure_datetime)\nGROUP BY closure_datetime"
    }
   ]
  },
  {
   "title": "Total Engagement By Employee",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(closure_datetime) as time_sec,\n  count(*) as value,\n  employees.full_name as metric\nFROM summary smm\nINNER JOIN employees ON employees.id = smm.employee_id\nWHERE $__timeFilter(closure_datetime)\ngroup by metric, time_sec\norder by time_sec"
    }
   ]
  },
  {
   "title": "Expenses By Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(payment_datetime) as time_sec,\n  sum(payment) as value,\n  payment_type as metric\nFROM payments\nWHERE $__timeFilter(payment_datetime)\nGROUP BY time_sec, metric"
    }
   ]
  },
  {
   "title": "Reports Generated By Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(generation_datetime) as time_sec,\nCOUNT(*) as value,\n  report_type as metric\nFROM report_generations\nWHERE $__timeFilter(generation_datetime)\nGROUP BY report_type, generation_datetime"
    }
   ]
  }
 ]
}